### PR TITLE
Give a name to spawned threads

### PR DESCRIPTION
**Pull request by linkmauve**
It helps when debugging which thread is which in a random program.

### CODE REVIEW

**Comment by nickbrowne** [comment]
Thanks a lot for this PR, I'm just getting over a cold at the moment but will hopefully review and merge within the next few days. Sorry to keep you waiting.

**Comment by linkmauve** [comment]
No problem, my game won’t be finished before you merge this PR. ^^

But get well soon! :)

**Comment by linkmauve** [comment]
Hi, have you had time to review this PR?  I might start using this crate in a project soon.

**Comment by nickbrowne** [comment]
Ah sorry, I just forgot, we can merge this :)

**Pull request merged**
