### PR TITLE
Run rustfmt on the entire codebase

### PR DESCRIPTION
**Pull request by linkmauve**
That makes it more coherent with the rest of the ecosystem.

I disabled rustfmt for `src/presets.rs`, as it was making it a lot more unreadable, if you want to do that on other parts of the code let me know.

Note that existing PRs will have to be rebased after this gets merged.

### CODE REVIEW

**Comment by linkmauve** [comment]
This PR has been updated to ignore `src/presets.rs`, and should be mergable again.

**Comment by linkmauve** [comment]
Updated again after merging #12.

**Comment by nickbrowne** [comment]
Sorry to be a pain but would you be able to rebase this again? I finally merged the bug fixes for the music buffers that had been sitting around in a branch for ages.

**Comment by linkmauve** [comment]
There, rebased.

And that’s not being a pain, that’s improving things, there is quite a difference actually. :p

**Comment by nickbrowne** [comment]
Thanks :)

**Pull request merged**
